# Generated by Django 3.0.7 on 2020-06-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDIHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdi_date', models.DateField(verbose_name='CDI date')),
                ('cdi_tax_rate', models.FloatField()),
            ],
        ),
    ]
