# Generated by Django 3.0.7 on 2020-06-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdihistory',
            name='cdi_date',
            field=models.DateField(unique=True, verbose_name='CDI date'),
        ),
    ]
